dependencies:
  # - <Organization>/<Repository>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

dotenv: .env

networks:
  sepolia:
    verify: True
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
  mainnet-fork-dev:
    verify: False
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
  development:
    verify: False
  ganache-local:
    verify: False
